name = "D&J Minecraft Server Modpack"
author = "curtbushko"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b88748c66f54359d1ce8ca93c4472af58f65312d95f3f2809b12b912e60148a3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
acceptable-game-versions = ["1.21.x"]
